### ISSUE TITLE
User Profile Page

### ISSUE THREAD

**Issue by leroynle** [cs130-w21/7#10]
## User Story
As a potential user, I would like to have a setting page so that I am able to change my profile as well as my password.

## Tasks
- [x] Front End #24 
- [x] Fetch User information from Database #25
- [x] Display user Information accordingly #26
- [x] Add validations for input field #28
- [x] Change User's profile #78
- [x] Change Email and Password #29
