### ISSUE TITLE
Main Page

### ISSUE THREAD

**Issue by TonyYounCH** [cs130-w21/7#30]
## User Story
As a frontend developer, I would like create a main page so that users can browse the website.

## Detailed Description
Main page with relevant video and tabs. 
Want to create responsive page.

## Tasks
- [x] Play video on landing page #31
- [x] Make responsive Navbar #32
- [x] Link to Log In / Sign Up page
