### ISSUE TITLE
Create an Event

### ISSUE THREAD

**Issue by leroynle** [cs130-w21/7#5]
## User Story
As a potential user, I would like to have the functionality of creating an event/party so that I can search for recommendations for my event.
## Acceptance Criteria
- [x] Add button to create an event #62
- [x] Event details page #118 
- [x] Create event page #119
