### ISSUE TITLE
Working With Users

### ISSUE THREAD

**Issue by leroynle** [cs130-w21/7#7]
### Description and User Benefit:
The user profile feature allows users to store data like email, username, password to the database system. Users can sign up via email or google account, and sign in to the app. The feature also lets users edit their profile and change password securely.

### User Actions:
- Users should be able to sign up via email or google account.
- Users should be able to sign in to the app.
- Users should be able to edit profiles on the setting page.
- Users should be able to change the username/password on the setting page.

## User Stories
- [x] Create a sign up page #8
- [x] Create a sign in page #9
- [x] Create user profile page  #10
